const permissions = {
  superadmin: {
    routePaths: [
      "dashboard",
      "profile",
      "owner-management",
      "alerts",
      "store-management",
      "genie-requests",
      "uploaded-files",
      "product-import",
      "import-history",
      "all-payment-methods",
      "add-payment-method",
      "all-subscriptions",
      "add-subscription",
    ],
  },
  owner: {
    routePaths: [
      "dashboard",
      "profile",
      "recent-products",
      "qr-scan-activity",
      "employee-management",
      "landing-page-configuration",
      "landing-preview",
      "qrscan-analytics",
      "qr-code-management",
      "qr-code-generator/settings",
      "add-qr-print",
      "review-qr-print",
      "quote-and-lead",
      "billing",
      "history",
      "product-catalog",
      "product-category",
      "product-vendor",
      "product-tag",
      "import-history",
    ],
  },
  manager: {
    routePaths: [
      "dashboard",
      "profile",
      "recent-products",
      "qr-scan-activity",
      "product-catalog",
      "qr-code-management",
      "qr-code-generator/settings",
      "add-qr-print",
      "review-qr-print",
      "landing-page-configuration",
      "landing-preview",
      "quote-and-lead",
      "employee-management",
      "import-history",
    ],
  },
  employee: {
    routePaths: [
      "dashboard",
      "profile",
      "recent-products",
      "qr-scan-activity",
      "product-lookup",
      "qr-code-management",
    ],
  },
};

export default permissions;
